# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '3376f1b9-a61c-48dd-9eb7-880170e5222f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Balaur_Bogdan'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bbogdy89/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    csmParametersFileLink: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

